version: '3.1'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elastic_net

  kibana:
    container_name: kibana
    image: kibana
    ports:
      - 5601:5601
    networks: 
      - elastic_net
    depends_on: 
      - elasticsearch

  logstash:
    container_name: logstash
    image: logstash
    volumes:
      - ./:/config-dir
    command: logstash -f /config-dir/logstash.conf
    networks: 
      - elastic_net
    depends_on: 
      - elasticsearch

networks: 
  elastic_net: